name: Docker build and push

on:
  push:
    branches:
      - 'feature/use_buildx'

env:
  IMAGE_NAME: larmic/tp-link-hs110-api

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64,arm

      - name: prepare buildx
        run: |
          # Use docker-container driver to allow useful features (push/multi-platform)
          docker buildx create --driver docker-container --use
          docker buildx inspect --bootstrap

      - name: build image
        run: |
          update-binfmts --enable # Important: Ensures execution of other binary formats is enabled in the kernel
          docker buildx build --pull -t "$IMAGE_NAME" .

      - name: docker images
        run: |
          docker images