name: Docker build and push

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_NAME: larmic/tp-link-hs110-api

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up image names
        run: |
          echo "LATEST_IMAGE=$IMAGE_NAME:latest" >> $GITHUB_ENV
          echo "TIMESTAMP_IMAGE=$IMAGE_NAME:$(date +'%Y-%m-%d-%s')" >> $GITHUB_ENV

      - name: Set up Go 1.15.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Go get dependencies
        run: go mod download

      - name: Go Test
        run: go test -v ./...

      - name: Go Build
        run: CGO_ENABLED=0 GOOS=linux go build -v ./...

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build amd64 image
        run: |
          DOCKER_BUILDKIT=1 docker build --build-arg=CGO_ENABLED=$CGO_ENABLED --build-arg=GOARCH=$GOARCH --tag $IMAGE_NAME:amd64 .
          docker push $IMAGE_NAME:amd64
        env:
          CGO_ENABLED: 0
          GOARCH: amd64

      - name: Build arm32v7 image
        run: |
          DOCKER_BUILDKIT=1 docker build --build-arg=CGO_ENABLED=$CGO_ENABLED --build-arg=GOARCH=$GOARCH --build-arg=GOARM=$GOARM --tag $IMAGE_NAME:arm32v7 .
          docker push $IMAGE_NAME:arm32v7
        env:
          CGO_ENABLED: 0
          GOARCH: arm
          GOARM: 7

      - name: Build arm64v7 image
        run: |
          DOCKER_BUILDKIT=1 docker build --build-arg=CGO_ENABLED=$CGO_ENABLED --build-arg=GOARCH=$GOARCH --build-arg=GOARM=$GOARM --tag $IMAGE_NAME:arm64v7 .
          docker push $IMAGE_NAME:arm32v7
        env:
          CGO_ENABLED: 0
          GOARCH: arm64
          GOARM: 7

      - name: List Docker images
        run: docker images

      - name: Build docker manifest
        run: |
          docker manifest create $LATEST_IMAGE --amend $IMAGE_NAME:amd64 --amend $IMAGE_NAME:arm32v7 --amend $IMAGE_NAME:arm64v7
          docker manifest annotate $LATEST_IMAGE $IMAGE_NAME:arm32v7 --os linux --arch arm
          docker manifest annotate $LATEST_IMAGE $IMAGE_NAME:arm64v7 --os linux --arch arm64
          docker manifest push $LATEST_IMAGE

          docker manifest create $TIMESTAMP_IMAGE --amend $IMAGE_NAME:amd64 --amend $IMAGE_NAME:arm32v7 --amend $IMAGE_NAME:arm64v7
          docker manifest annotate $TIMESTAMP_IMAGE $IMAGE_NAME:arm32v7 --os linux --arch arm
          docker manifest annotate $TIMESTAMP_IMAGE $IMAGE_NAME:arm64v7 --os linux --arch arm64
          docker manifest push $TIMESTAMP_IMAGE
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled