name: Docker build and push

on:
  push:
    branches:
      - 'main'

env:
  TIMESTAMP_IMAGE_TAG: $(date +%s)

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go 1.15.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Test
        run: go test -v ./...

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux go build -v ./...

      - name: Build the Docker image
        run: DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag larmic/tp-link-hs110-api:latest

      - name: Tag the Docker image with current timestamp
        run: docker tag larmic/tp-link-hs110-api:latest larmic/tp-link-hs110-api:${{ IMAGE_TAG }}
        env:
          IMAGE_TAG: ${{ TIMESTAMP_IMAGE_TAG }}

      - name: List Docker images
        run: docker images

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to DockerHub
        run: |
          docker push larmic/tp-link-hs110-api:latest
          docker push larmic/tp-link-hs110-api:${{ IMAGE_TAG }}